config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'home/about' => 'homes#about'
  devise_for :users
  resources :users, only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings', to: 'relationships#followings', as: 'followings'
    get 'followers', to: 'relationships#followers', as: 'followers'
    # relationships は中間テーブルなので、usersモデルにネストさせる。
    # URLからparamsで:user_idと:idを受け取ることができる。
  end

  resources :books do
    resources :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy


  # 多対多の関係をリレーショナルデータベースでは直接表現できないので、中間テーブルを使って表現するのが一般的。
  # リレーショナルデータベースとは、行と列によって構成された「表形式のテーブル」と呼ばれるデータの集合を、互いに関連付けて関係モデルを使ったデータベースのこと。

  #＜解説＞
  # 参照先のusersテーブルと参照元のrelationshipsテーブルのアソシエーションをhas_manyメソッドによって宣言する。
  # それによって、参照先の主キー:idと参照元の外部キー:followed_idを対応させ、参照先の主キーから参照元の複数のレコードを取得できるようにする。
  # has_manyの関連名には参照元のモデル名を記述するが、今回は関連名をreverse_of_relationshipsにする。
  # 関連名がモデル名でないので、:class_nameを使ってモデル名を指定する必要がある。
  # relationshipsテーブルにある、userテーブルの外部キーのカラム名は、:user_idではなく、:followed_idである。
  # :モデル名_idではないため、:foreign_keyを使って外部キーを指定する必要がある。
  # dependent: :destroyでオーナーオブジェクトがdestroyされたときに関連付けされたオブジェクトをすべて同時にdestroyされる。
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  #＜解説＞
  # 関連名reverse_of_relationshipsのアソシエーションで、中間テーブルの外部キーfollowed_idを参照先のusersテーブルの主キー:idと対応させた。
  # 関連名followerのアソシエーションで、中間テーブルの外部キーfollowed_idを参照元のusersテーブルの主キーと対応させた。
  # 参照先のusersテーブルと参照元のusersテーブルのアソシエーションをhas_many throughメソッドによって宣言する。
  # それによって、参照先の主キーと参照元の主キーを対応させ、参照先の主キーから参照元の複数のレコードを取得できるようにする。
  # has_manyの関連名には参照元のモデル名を記述するが、今回は関連名をfollowersにする。
  # through: には参照先と中間テーブルのアソシエーションの関連名を記述する。
  # 今回の場合だと、reverse_of_relationshipsを記述する。
  # source: には「ソース」の関連名を記述する。
  # [ソース」とは主に情報の出どころ、出典、情報源のことを指します。
  # ここでの「ソース」は参照元のこと。つまり、参照元の主キーと対応させたアソシエーションの関連名を記述する。
  # 今回の場合だと、relationship.rbのアソシエーションで宣言された関連名を記述する。
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  attachment :profile_image, destroy: false

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction,  length: { maximum: 50 }

# 解説
# 関連名relationshipsは、名前そのものが参照元のテーブルを取得するためのアクセサーメソッドになる。
# インスタンスメソッドrelationshipsはオブジェクトを必要とするが、relationships.create(followed_id: user_id)はインスタンスメソッドfollow(user_id)のオブジェクトに対して実行される処理である。
# なので、relationshipsメソッドのオブジェクトはインスタンスメソッドfollow(user_id)と同じオブジェクトとなる。
# follow(user)メソッドのオブジェクトに対して、relationshipsメソッドで参照元のrelationshipsテーブルのレコードを取得する。（そのレコードを扱うRelationshipモデルクラスのインスタンスを生成する）
# そのインスタンスのcreateメソッドで、インスタンスが扱っているレコードのカラム:followed_idの値をすべて引数user_idの値にしたレコードを扱うモデルのインスタンスを生成して、レコードをデータベースに保存する。
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end


# 解説
# 関連名relationshipsは、名前そのものが参照元のテーブルを取得するためのアクセサーメソッドになる。
# インスタンスメソッドrelationshipsはオブジェクトを必要とするが、relationships.find_by(followed_id: user_id).destroyはインスタンスメソッドunfollow(user_id)のオブジェクトに対して実行される処理である。
# なので、relationshipsメソッドのオブジェクトはインスタンスメソッドunfollow(user_id)と同じオブジェクトとなる。
# unfollow(user)メソッドのオブジェクトに対して、relationshipsメソッドで参照元のrelationshipsテーブルのレコードを取得する。（そのレコードを扱うRelationshipモデルクラスのインスタンスを生成する）
# そのインスタンスのfind_byメソッドで、インスタンスが扱っているレコードのカラムfollowed_idの値が引数user_idの値と同じレコードを上から一つ取得する。（そのレコードを扱うRelationshipモデルクラスのインスタンスを生成する）
# そのインスタンスのdestroyメソッドによって、レコードをテータベースから削除する
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  # 解説
  # 関連名followingは、名前そのものが参照元のテーブルを取得するためのアクセサーメソッドになる
  # インスタンスメソッドfollowingsはオブジェクトを必要とするが、followings.include?(user)はインスタンスメソッドfollowing?(user)のオブジェクトに対して実行される処理である。
  # なので、followingsメソッドのオブジェクトはインスタンスメソッドfollowing?(user)と同じオブジェクトとなる。
  # following?(user)メソッドのオブジェクトに対して、follwingsメソッドで参照元のusersテーブルのレコードを取得する。（そのレコードを扱うUserモデルクラスのインスタンスを生成する）
  # そのインスタンスのinclude?メソッドでフィールドに引数userの値と等しいあるかどうか真偽値を返す。
  # 等しい値がある場合はtrue
  def following?(user)
    followings.include?(user)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <!--Userモデルのインスタンスuserのfollowingsメソッドを宣言する。
        参照先テーブルusersの:idから中間テーブルrelationshipsの外部キーfollower_idを介し、follower_idに対応したfolloed_idを外部キーとした参照元のusersテーブルのレコードを取得して、そのレコードの数を数える-->
        <td>フォロワー数: <%= user.followers.count %></td>
        <!--Userモデルのインスタンスuserのfollowersメソッドを宣言する。
        参照先テーブルusersの:idから中間テーブルrelationshipsの外部キーfollowed_idを介し、followed_idに対応したfolloer_idを外部キーとした参照元のusersテーブルのレコードを取得して、そのレコードの数を数える-->
        <td>
          <%# byebug %>
          <% if current_user.following?(user) %>
          <!--引数の-->
            <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete %>
          <% else %>
            <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th>
      <%= link_to user_followings_path(user.id) do %>
        <%= user.followings.count %>
      <% end %>
    </th>
  </tr>
  <tr>
    <th>followers</th>
    <th>
      <%= link_to user_followers_path(user.id) do %>
        <%= user.followers.count %>
      <% end %>
    </th>
  </tr>
  <tr>
    <td>
      <%# byebug %>
      <% if current_user.following?(user) %>
      <!--引数の-->
        <%= link_to "フォローを外す", user_relationships_path(user.id), class: "btn btn-primary", method: :delete %>
      <% else %>
        <%= link_to "フォローする", user_relationships_path(user.id), class: "btn btn-primary", method: :post %>
      <% end %>
    </td>
  </tr>
</table>

<div class='row'>
  <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
    	<%= render 'layouts/errors', obj: @book %>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>