config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'home/about' => 'homes#about'
  devise_for :users
  resources :users, only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings', to: 'relationships#followings', as: 'followings'
    get 'followers', to: 'relationships#followers', as: 'followers'
    # relationships は中間テーブルなので、usersモデルにネストさせる。
    # URLからparamsで:user_idと:idを受け取ることができる。
  end

  resources :books do
    resources :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

end

app/models/book.rb
class Book < ApplicationRecord

	# BookモデルとUserモデルをbelongs_toで関連付けしている。
	# :userはメソッド名であり、userメソッドを定義している。
	# userメソッドは、Userモデルのインスタンスを生成し、それを戻り値として返すメソッドである。
	belongs_to :user
	# BookモデルとFavoriteモデルをhas_manyで関連付けしている。
	# :favoritesはメソッド名であり、favoritesメソッドを定義している。
	# favoritesメソッドは、Favoriteモデルのインスタンスを生成し、それを戻り値として返すメソッドである。
	has_many :favorites, dependent: :destroy

	has_many :book_comments, dependent: :destroy

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	# Bookモデルクラスのインスタンスメソッド、favorited_by?メソッドを定義する
	# 上記の記述によりBookモデルクラスとfavoriteモデルクラスは関連付けされた。
	# 関連付けされたことによって、Bookモデルクラスにfavoritesメソッドが定義された。
	# favoritesメソッドは、Favoriteモデルクラスのインスタンスを生成し、それをを戻り値として返す。
	# favoritesメソッドによって生成したFavoriteモデルのインスタンスは、whereメソッドによって、
	# favoritesテーブルの中から、引数のidメソッドの戻り値idと同じ値のuser_idを持つ
	# レコードを見つけ、配列として返す。
	# exists?が、その配列内にレコードがあるかどうかの真偽値を返す。
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = @book.user
    @book_comment = BookComment.new
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render "index"
    end
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user_id == current_user.id
      redirect_to books_path
    end
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user) do %>
            <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td>
          <% if book.favorited_by?(current_user) %>
            <p>
              <!--pry-byebugを使ってbook_favorite_pathを確認したとき引数にキーが2つ必要であることを確認できた-->
              <!--パスの指定の際に引数に:book_idと:idの二つが必要になる-->
              <!--引数の書き方がキーワード引数であっても、通常の引数であっても動作した。-->
              <%= link_to book_favorite_path(book_id: book, id: book.favorites), class: "text-danger", method: :delete do %>
                ♡<%= book.favorites.count %>
              <% end %>
            </p>
          <% else %>
            <p>
              <%= link_to book_favorites_path(book), method: :post do %>
                ♡<%= book.favorites.count %>
              <% end %>
            </p>
          <% end %>
        </td>
        <td>
          <p>
            コメント数:<%= book.book_comments.count %>
          </p>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
    	<%= render 'layouts/errors', obj: @book %>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user  %>
      <h2 class="mt-3">New book</h2>
    	<%= render 'layouts/errors', obj: @book_new %>
      <%= render 'form', book: @book_new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
  		    <td><%= link_to user_path(@book.user) do %>
            <%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>
          <td>
            <% if @book.user_id == current_user.id %>
              <%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %>
            <% end %>
          </td>
          <td>
            <% if @book.user_id == current_user.id %>
              <%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%>
            <% end %>
          </td>
          <td>
            <% if @book.favorited_by?(current_user) %>
              <p>
                <%= link_to book_favorite_path(book_id: @book, id: @book.favorites), class: "text-danger", method: :delete do %>
                  ♡<%= @book.favorites.count %>
                <% end %>
              </p>
            <% else %>
              <p>
                <%= link_to book_favorites_path(@book), method: :post do %>
                  ♡<%= @book.favorites.count %>
                <% end %>
              </p>
            <% end %>
          </td>
          <td>
            <p>
              コメント数:<%= @book.book_comments.count %>
            </p>
          </td>
        </tr>
      </table>

      <table class='table'>
        <tbody>
          <% @book.book_comments.each do |book_comment| %>
            <tr>
              <td>
                <%= link_to user_path(book_comment.user) do %>
                  <%= attachment_image_tag(book_comment.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
                <% end %><br>
                <%= link_to user_path(book_comment.user) do %>
                  <%= book_comment.user.name %>
                <% end %>
              </td>
              <td>
                <p>
                  <%= book_comment.comment %>
                </p>
              </td>
              <td>
                <% if @book.user == current_user %>
                  <%= link_to "Destroy", book_book_comment_path(book_id: book_comment.book, id: book_comment), method: :delete, class: "btn btn-danger" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="new-comments">
        <%= form_with model: @book_comment, url: book_book_comments_path(@book), method: :post, local: true do |f| %>
          <%= f.text_area :comment %>
          <%= f.submit "送信" %>
        <% end %>
      </div>
    </div>
  </div>
</div>